feat(makefile): Update makefile
freelawproject/courtlistener pull request #2143
Opened 2022-07-06 17:42 UTC by flooie

Add multiarch development push
Simplify development image builds

@mlissner I think it makes sense to add a multi arch push for development images, but 
I'm hesitant to just include it in the normal process for pushing builds for the server. 

I also dropped the tagging of web dev versions because ... who is using those anyway.

2022-07-08 17:48 UTC, flooie commented
@mlissner only the web-dev was being built and not pushed right?  I think we should build a celery-dev too agreed?

2022-07-08 17:58 UTC, mlissner commented
I guess if we are running the `push` command, it should build everything that it tries to push or else the push is buggy?

2022-07-20 22:08 UTC, mlissner requested changes

2022-07-20 22:08 UTC, mlissner commented on .github/workflows/docker-build-dev.yml
> +name: Automate build and deploy
```suggestion
name: Push new dev images
```

2022-07-20 22:08 UTC, mlissner commented on .github/workflows/docker-build-dev.yml
> +          make multiarch_push_development --file docker/django/Makefile
```suggestion
          make multiarch_push_development --file docker/django/Makefile  -e VERSION=$(git rev-parse --short HEAD)
```

2022-07-23 01:35 UTC, mlissner approved these changes

2022-07-23 01:42 UTC, merged