Feat: first pass at db model for record of citation by RECAP document
freelawproject/courtlistener pull request #2439
Opened 2023-01-01 16:46 UTC by ss108

Here is my first take at the DB model for keeping track of citations from RECAP documents (such as briefs) to court opinions. 

The most difficult part of this portion of the full feature is naming this model/table.

2023-01-01 16:49 UTC, johnhawkinson commented
Is it worth considering citation **to** other RECAP documents that are not opinions (e.g. motions, briefs)?

2023-01-01 17:01 UTC, ss108 commented
Well, I guess I will figure out the migration issue once you guys approve the contents of the model.

@johnhawkinson IDK if you're asking me or Mike only, but the basics of my thoughts on that are that it depends on whether you want to prioritize surfacing/exposing as much info as possible versus want to improve the user experience.

2023-01-01 17:02 UTC, johnhawkinson commented
I'm just suggesting that we are often stuck with DB models for decades, so it is wise to consider future work when defining the model. I offer no opinion as to who should respond.

2023-01-01 17:10 UTC, ss108 commented
Good point. 

Seems like a citation to a docket entry would be a different model though.

2023-01-04 01:23 UTC, mlissner commented
> Is it worth considering citation to other RECAP documents that are not opinions (e.g. motions, briefs)?

No, it's not really worth it for now, beyond realizing that such a feature would just require a new table. New tables are easy. Hard tables are the ones that add or remove columns from big tables. Thanks for raising this though.

2023-01-04 01:27 UTC, mlissner requested changes
Yeah, this is about right. I think you pretty much nailed the model name. I think I'd go with `OpinionsCitedByRECAPDocument` though, if you don't mind tweaking that in the class name and the verbose_name_plural, that'd be great. 

The one other thing we need here is migration SQL. See [here](https://github.com/freelawproject/courtlistener/blob/main/DEVELOPING.md#special-notes-for-special-types-of-code) for a few (brief) details. If you think more would be helpful, feel free to add that to this PR. (Our docs can always be improved and you're the perfect person to do so.)

Otherwise, this looks good to me, thanks.

2023-01-04 01:29 UTC, mlissner commented
Oh, and I guess @ss108, if you want to really dial things in, we do have a commit message template you could apply. I don't usually bug volunteers about it, but since you've been around awhile, I'm guessing you'd actually care. See item three here: 

https://github.com/freelawproject/courtlistener/blob/main/DEVELOPING.md#guidelines-for-contributions

Thank you again!

2023-01-07 23:21 UTC, ss108 commented
@mlissner do you want me to put the generated SQL anywhere, or does it not matter, given that we know we aren't going to run into known issues?

2023-01-07 23:23 UTC, mlissner commented
Usually we just put it next to the migration file with an sql extension and the same file name, and that's it.

2023-01-13 21:02 UTC, ss108 commented
@mlissner I think this is a good cutoff point to merge. What do you think?

2023-01-13 23:50 UTC, mlissner requested changes
Sorry for the slowness reviewing. I didn't realize it was ready for me. I found one other small thing that could be better, if you don't mind. Things should get smoother once this is merged!

2023-01-13 23:50 UTC, mlissner commented on cl/search/models.py
> +        db_index=True,
Sorry, I just caught one more thing. This [should be done in the `indexes` meta attribute](https://github.com/django/django/pull/12716). It's easier to adjust and manage when it's there. Probably I should teach semgrep to throw an alert when db_index is used...someday. 

Anyhow, mind making that last tweak, and then we'll be good to go?

2023-01-13 23:51 UTC, mlissner commented on cl/search/models.py
> +        db_index=True,
And in case it's not obvious, after you do this, the SQL migration and the migration file both probably need regeneration.

2023-01-16 14:24 UTC, ss108 commented
@mlissner is this right?

I read the PR you linked to and the threads linked therein. Seems like the issue is that using `db_index=True` actually creates 2 indices, thus taking up extra disk space? And additionally, is harder to update and manage going forward, for whatever reason? Do I have that about right?

2023-01-18 01:28 UTC, mlissner commented
Yeah, I think you have that right. I think the bottom line is that Django tried to be helpful when you set db_index=True, but over the years Django supported more kinds of indexes, so now it's best to do them using the more featureful meta parameter. In my experience the ones made with the meta parameter are much easier to reconfigure and deal with than the traditional ones.

2023-01-18 01:30 UTC, mlissner approved these changes
This looks great. I'll get it deployed tomorrow.

2023-01-18 01:30 UTC, mlissner commented on cl/search/models.py
> +        # db_index=True,
```suggestion
```

2023-01-18 04:26 UTC, merged

2023-01-18 13:36 UTC, ss108 commented
Thanks. I have started on the actual functionality.

2023-01-18 18:03 UTC, mlissner commented
Our pleasure, thank you.