Add previous/next navigation buttons to the filter bar.
freelawproject/courtlistener pull request #2687
Opened 2023-04-27 16:12 UTC by troglodite2

Currently dockets have upto 200 entries on them.  We have navigation buttons at the very bottom that allow navigation.  Many people use scrolling to move through a page and a 200 item docket can be time consuming.

We add Previous and Next buttons to the filter bar to allow people to navigate more easily when at the top of the page.

During testing it became apparent that the Bootstrap XS version was pretty ugly, per CL design specifications.  Code was added to override.css to make things look better.

When testing at a screen width of 360px it again looked horrible. Having things look right at XS width and at 360 wasn't possible.

To allow for another breakpoint a series of classes were added to override.css that provide cl-col-xxs- and cl-col-xs- as well as some auxilary classes.  These allow for that extra breakpoint.

the cl-col-xs- are required because the col-xs- classes are always "on" and we needed a method to override them.

We also added some specific cl-pull classes to allow different alignment based on screen size.

Fixes: #2670

2023-04-27 16:19 UTC, mlissner commented
What happened to the boostrap-sm that you had here: https://github.com/freelawproject/courtlistener/issues/2670#issuecomment-1524120128

2023-04-27 16:23 UTC, troglodite2 commented
I can try to get back to it.  I think going from small to large, I kept the wrong look.

2023-04-27 17:35 UTC, troglodite2 commented
Per discussions, we are designing this for standard bootstrap break points.  The 360px is what it is.
360px:
![image](https://user-images.githubusercontent.com/82225842/234942918-16e6b512-75d3-421e-871a-f588ff646b29.png)
Bootstrap xs: 767px:
![image](https://user-images.githubusercontent.com/82225842/234943060-477ba4b2-5149-4446-83f8-4878197e89bf.png)
Bootstrap sm: 991px
![image](https://user-images.githubusercontent.com/82225842/234943155-c48fd7ff-6780-4bf8-a098-21264719e206.png)
Bootstrap md: 1199px
![image](https://user-images.githubusercontent.com/82225842/234943263-063e617a-cba3-4915-933e-f278511fd144.png)
Bootstrap lg and desktop: 1500px
![image](https://user-images.githubusercontent.com/82225842/234943445-75496da9-2dd5-45e6-ad5d-bb25e4980434.png)

Once these images are approved, I'll push up the next commit.

2023-04-27 20:14 UTC, mlissner commented
These look good, but the screenshots aren't the most difficult widths. 767, 991, and 1199 are the best cases for xs, sm, and md sizes. The harder question is one pixel bigger: The smallest size before the breakpoint kicks in. Can you share 768, 992, and 1200? 

My general feedback though is we should try to stick to two lines max, except on xs, and should drop pagination on the smaller sizes if we need to, to make that happen.

2023-04-27 20:19 UTC, troglodite2 commented
768px:
![image](https://user-images.githubusercontent.com/82225842/234981099-f8262a62-1647-46ac-bac3-75bf30c30513.png)
992px:
![image](https://user-images.githubusercontent.com/82225842/234981490-28e0e426-0276-4337-b329-e074c53f12e2.png)
1200px:
![image](https://user-images.githubusercontent.com/82225842/234981636-62956513-c900-4149-b065-699f27bd593e.png)

2023-04-27 20:21 UTC, mlissner commented
Cool. Those look great. Do what you can for xs, and let's ship.

2023-04-27 20:55 UTC, mlissner requested changes
A couple little CSS things, but we're on the homestretch.

2023-04-27 20:55 UTC, mlissner commented on cl/assets/static-global/css/override.css
> +    float: right !important;
I don't think we need to namespace these, and it seems like the convention in BS4 and BS5 is to call them `pull-right-xs` and and `pull-left-xs`.

2023-04-28 04:09 UTC, mlissner approved these changes

2023-04-28 04:09 UTC, merged