cleaning git commits for recap doc updates
freelawproject/courtlistener pull request #2903
Opened 2023-07-17 19:16 UTC by ss108

2023-07-17 19:27 UTC, ss108 commented on .gitignore
> -cl/node_modules
This `cl/node_modules` is deleted because it is a duplicate.

2023-07-17 19:29 UTC, mlissner requested changes
I wouldn't ask for any more changes, but if we stop ignoring the node_modules folder, that'll be a problem. So, two more little things for you, then we're ready.

2023-07-17 19:29 UTC, mlissner commented on .gitignore
> -cl/node_modules
This still shouldn't be deleted.

2023-07-17 19:29 UTC, mlissner commented on cl/citations/tasks.py
> +    )  # even though this function assumes the input is an opinion, it will work for RECAP documents.
This comment exceeds our max line length.

2023-07-17 19:32 UTC, mlissner commented
Automerge is set. Thank you for your patience and sticking to this one. Next step: Sucking out millions of citations!

2023-07-18 20:39 UTC, mlissner approved these changes

2023-07-18 20:39 UTC, merged

2023-07-18 20:39 UTC, mlissner commented
OK, and we're merged!