3222 Update Coverage
freelawproject/courtlistener pull request #3241
Opened 2023-10-11 18:35 UTC by flooie

PR includes more updates 

Spinner for long running tasks
Adds 7 Day cache from 1 day

Updates language on coverage pages and table of contents
Cleans up various sentences and style choices

Adds support for mobile and dynamically adjusts margins 
as well as resize the chart for a broad range of sizes

Drops the sidebar on mobile - and switches (to court IDs) on small
screens.  

We do not have consistent small enough labels so ID is used.  

Removed chartographer.js and coverage.js in simple pages

2023-10-11 21:40 UTC, mlissner requested changes
Thanks Bill. I haven't looked too deeply at the JS, I'm hoping @ERosendo could do that, but I do have a couple other comments. 

Also, you can remove plottable and d3 from the page too, right?

Finally, can you share some screenshots?

What is id=json-data?

2023-10-11 22:05 UTC, flooie commented on cl/simple_pages/templates/help/coverage_opinions.html
> +    </style>
that wasn't supposed to be there.

2023-10-11 22:22 UTC, flooie commented
This is the top when the dimensions are smaller than an iPhone.  

<img width="393" alt="Screenshot 2023-10-11 at 6 16 53 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/76eac4be-8d34-4c6e-ae8d-b58e95ad7a6d">

The dreaded Ohio Examples 
Each of which is exaggerated by my ability to take super long screenshots but I felt it useful.  
<img width="765" alt="Screenshot 2023-10-11 at 6 19 57 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/94bf997d-4a1b-4c9f-8c77-3ece9fa7b54c">
<img width="431" alt="Screenshot 2023-10-11 at 6 20 11 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/68f82bd5-41fe-46c6-84b4-b078e1c386b3">
<img width="267" alt="Screenshot 2023-10-11 at 6 20 19 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/dd7f3d73-8aad-44eb-ac26-f42f3b0ea961">


Finally some standard shots one with names and one with IDs 
<img width="779" alt="Screenshot 2023-10-11 at 6 19 10 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/6f464b62-41be-48b9-aaa1-0878e296983f">
<img width="456" alt="Screenshot 2023-10-11 at 6 19 30 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/9325538a-ee86-4867-b695-8a7651e3bd3c">

2023-10-13 14:51 UTC, ERosendo approved these changes
The JS code looks good! 👍

2023-10-13 17:52 UTC, mlissner approved these changes
Cool, let's give it a go.

2023-10-13 17:52 UTC, mlissner commented on cl/simple_pages/templates/help/coverage.html
>          <script src="{% static "js/d3.js" %}"></script>
Are we still using d3 on this page?

2023-10-13 17:52 UTC, merged

2023-10-13 17:54 UTC, flooie commented on cl/simple_pages/templates/help/coverage.html
>          <script src="{% static "js/d3.js" %}"></script>
sure doesnt look like it