feat(scrapers): support nytrial scrapers
freelawproject/courtlistener pull request #3577
Opened 2024-01-08 17:41 UTC by grossir

Theses changes are needed to support freelawproject/juriscraper#827

- If possible, get court object from child_court field passed by nytrial families of scrapers. Otherwise, default to parent court. This does not alter behavior for other sources. Solves freelawproject/juriscraper#847
- Pass opinion.html to site.extract_from_text, if opinion.plain_text does not exists. Solves #3549
- Add support to update Opinion object from extract_from_text metadata dict.

2024-01-09 01:24 UTC, flooie commented on cl/scrapers/management/commands/cl_scrape_opinions.py
> +                )
I wouldnt mind seeing the parameters names

2024-01-09 01:25 UTC, flooie commented on cl/scrapers/tasks.py
> +    metadata_dict = site.extract_from_text(opinion.plain_text or opinion.html)
Thanks for fixing this.

2024-01-09 01:27 UTC, flooie commented
I think you need to include the latest release of courts-db v0.10.21 to poetry. Otherwise I think this is complete

2024-01-09 01:27 UTC, flooie requested changes
Update courts-db to v0.10.21 please.

2024-01-09 22:28 UTC, grossir commented
I abstracted the behavior for child courts into get_child_court
I tested it locally creating the following courts:
```
from cl.search.models import Court

# Child court with expected parent
Court(id='nysupctnewyork', parent_court=Court.objects.get(pk='nysupct'), position='33.1', jurisdiction='TRT', full_name='New York County, Supreme Court', short_name='Test2').save()

# Child courts with unexpected parents, error should be logged and records saved with court id from scraper
Court(id='nysupctqueens', parent_court=Court.objects.get(pk='nysurct'), position='35.2', jurisdiction='TRT', full_name='Queens County, Supreme Court', short_name='Test3').save()
Court(id='nysupctkings', parent_court=Court.objects.get(pk='nysurct'), position='36.2', jurisdiction='TRT', full_name='Kings County, Supreme Court', short_name='Test3').save()
```
and checking that both logs and DB behaved as expected, and they did

2024-01-10 00:29 UTC, flooie commented on cl/scrapers/utils.py
> +def get_child_court(child_court_name: str, court: Court) -> Optional[Court]:
I would not pass the full court object when the string will do.

2024-01-10 00:31 UTC, flooie commented on cl/scrapers/management/commands/cl_scrape_opinions.py
> +            child_court = get_child_court(item.get("child_courts", ""), court)
something about this is weird to me ...

2024-01-10 00:32 UTC, flooie approved these changes
Thanks @grossir  for putting this through its paces.

2024-01-10 00:32 UTC, merged

2024-01-10 22:02 UTC, flooie commented
@grossir what say you?

2024-01-10 22:13 UTC, grossir commented
From the Sentry event, the child court name was  `'Ct Cl'` and the child court id was `nyclaimsct`
So, it found the "parent" court as child. 
I think this merits a new control in that function, to ensure that the child found actually has a parent.