feat(sentry): Group Sentry issues by scraper
freelawproject/courtlistener pull request #3603
Opened 2024-01-15 15:33 UTC by grossir

Uses Sentry's fingerprinting of events to force a grouping. 
For scraping and parsing errors, the desired grouping is by the data's source scraper, which can be identified by the juriscraper module. If the module is not available, by the court id

Solves #3399

2024-01-16 17:48 UTC, flooie commented on cl/settings/third_party/sentry.py
> +    event: Dict[str, Any], hint: Dict[str, Any]
typing can be lower case I think.  Atleast for dict.

2024-01-16 17:49 UTC, flooie commented on cl/settings/third_party/sentry.py
> +def fingerprint_event(
I think the name could be slightly more descriptive...

maybe something like ... `fingerprint_sentry_error`

2024-01-16 17:50 UTC, flooie commented on cl/settings/third_party/sentry.py
> +    :param event: event dict to be sent to Sentry
I guess im just mostly confused by this docstring- think you can take a crack at rewriting it.

2024-01-16 17:51 UTC, flooie requested changes
This is great.  @grossir 

Can you just rework the docstrings on the fingerprint function.  I found it hard to understand

2024-01-17 23:44 UTC, grossir commented
Hi @flooie please review again. Sorry about the messy commit history; I rebased the branch so that it was up to date with main but now all the commits are included in the PR. Still the files changed remain the same

- cl/settings/third_party/sentry.py
- cl/scrapers/management/commands/cl_scrape_opinions.py
- cl/scrapers/utils.py
- cl/scrapers/tasks.py

2024-01-18 18:03 UTC, merged

2024-01-23 17:39 UTC, flooie commented
> ## Suspect Issues
> This pull request was deployed and Sentry observed the following issues:
> 
> * ‼️ **SSLError: HTTPSConnectionPool(host='www.jud.ct.gov', port=443): Max retries exceeded with url: /external/su...** `cl.scrapers.management.commands.cl_scrape_opini...` [View Issue](https://freelawproject.sentry.io/issues/4908738955/?referrer=github-pr-bot)
> 
> Did you find this useful? React with a 👍 or 👎


this is in dev sentry - I was testing a known bug