feat(contact_form): Enable selection of issue type and enable Jira integration
freelawproject/courtlistener pull request #4605
Opened 2024-10-21 21:41 UTC by elisa-a-v

Addresses #4585 

This update enhances the contact form by allowing users to select the "Issue Type" for their submission, and also optionally pre-select it via URL query parameters, improving UX.

Additionally, the contact form now sends submissions to `support@freelawproject.atlassian.net`, integrating with Jira for better issue tracking. The email body includes:

- User Email: Displayed as `User Email: <email address>` to facilitate easy parsing in Jira.
- Issue Type: Clearly stated to assist in automatic categorization within Jira.
- Subject and Message: Retained as before for detailed context.

This change enables automatic ticket creation to relieve some of the overhead of managing requests manually by email.

2024-10-21 21:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/freelawproject/courtlistener?pullRequest=4605) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/freelawproject/courtlistener?pullRequest=4605) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/freelawproject/courtlistener?pullRequest=4605) it.</sub>

2024-10-21 21:45 UTC, elisa-a-v commented
@mlissner I had issues with the pre-commit when working on this which is why there are so many commits each doing very little, but I got it working now so it won't happen again!

I can revert them and add all the small changes in a single commit, please let me know if I should do it or just leave it as is.

2024-10-21 23:18 UTC, mlissner approved these changes
Looks good to me at a glance. Off to Eduardo for more careful review. The commits are fine, we can just squash when we merge.

Thank you and congrats on your first (official) PR!

2024-10-21 23:18 UTC, mlissner commented
@s-taube, before we merge this, have you had a chance to look at the security vuln I mentioned that this might open up?

2024-10-22 01:43 UTC, ERosendo commented on cl/simple_pages/forms.py
> +
We should adopt Django's recommendation of using named constants for each value of the iterable.

```suggestion
    REMOVAL_REQUEST = "removal"
    RECAP_BUG = "recap"
    SUPPORT_REQUEST = "support"
    ISSUE_TYPE_CHOICES = [
        (REMOVAL_REQUEST, "Case Removal Request"),
        (RECAP_BUG, "RECAP Extension Bug"),
        (ISSUE_TYPE_CHOICES, "Support"),
    ]
   VALID_ISSUE_TYPES = [REMOVAL_REQUEST, RECAP_BUG, SUPPORT_REQUEST]
```

By following this suggestion, we can write cleaner and more expressive checks, such as:

```python
if form.issue_type == ContactForm.REMOVAL_REQUEST
```

and 

```python
if issue_type in ContactForm.VALID_ISSUE_TYPES:
```

2024-10-22 01:51 UTC, ERosendo commented on cl/simple_pages/views.py
> +                initial["issue_type"] = issue_type_lower
if we apply the previous suggestion, we can refactor this code like this:

```suggestion
        if issue_type and issue_type.lower() in ContactForm.VALID_ISSUE_TYPES:
            initial["issue_type"] = issue_type.lower()
```

2024-10-22 02:17 UTC, s-taube commented
> @s-taube, before we merge this, have you had a chance to look at the security vuln I mentioned that this might open up?

Yes. As far as I can tell, this Zendesk issue should not impact Atlassian products at all.

2024-10-22 02:18 UTC, ERosendo requested changes
The code is looking great! Just a couple of small things to address before we can merge this PR.

2024-10-22 16:25 UTC, ERosendo approved these changes

2024-10-22 16:34 UTC, ERosendo commented
LGTM :shipit:

2024-10-22 16:39 UTC, merged

2024-10-22 16:40 UTC, mlissner commented
OK, here we go. Thanks everybody. @s-taube, in about ten minutes, when [this](https://github.com/freelawproject/courtlistener/actions/runs/11464656156) finishes, this code will be live and I think we'll be in Jira-land.

2024-10-22 16:40 UTC, mlissner commented
Thanks all!