Installed tailwind, added components page, created toy components with django-components and embedded Vue
freelawproject/courtlistener pull request #4800
Opened 2024-12-08 23:36 UTC by ashkonf

* https://github.com/freelawproject/courtlistener/issues/4736
* https://github.com/freelawproject/courtlistener/issues/4741
* https://github.com/freelawproject/courtlistener/issues/4738

2024-12-08 23:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/freelawproject/courtlistener?pullRequest=4800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/freelawproject/courtlistener?pullRequest=4800) before we can accept your contribution.<br/><hr/>**Ashkon Farhangi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/freelawproject/courtlistener?pullRequest=4800) it.</sub>

2024-12-11 04:49 UTC, mlissner commented
@ashkonf, can you please sign the CLA per the instructions above?

2024-12-14 23:07 UTC, mlissner requested changes
OK, this PR has a lot of bits to it to make things work, and most of it is so complicated/fragile I can barely figure it out. I think @ERosendo might have some better intuition, since he set up tailwind on Bots.law, but I did make a number of comments for things I noticed. 

I think we should approach this PR in two steps:

1. Focus on cleaning up the various configurations, settings, installations, etc, so they're polished and optimized.

    As part of this, I think we'll want to include the reloader in our docker-compose.yaml file, similar to how big cases does it.

3. Dial in the implementation of the two components, so we can see the parts that really matter.

@ashkonf, can you work on the comments I've made so far, and @ERosendo, can you review after that, please?

2024-12-14 23:07 UTC, mlissner commented on cl/assets/templates/base.html
> +  <link href="{% static "css/app.css" %}" rel="stylesheet">
I'm finding this a bit weird. We link to app.css, which imports tailwindcss. Gotta be a better way. I think Bots.law just has:

```
  {% tailwind_preload_css %}
  {% tailwind_css %}
```

Honestly not sure what the preload vs. regular do, but definitely simpler/cleaner?

2024-12-14 23:07 UTC, mlissner commented on cl/simple_pages/templates/components.html
> +{% load humanize %}
I don't think you need `humanize`, do you?

2024-12-14 23:07 UTC, mlissner commented on cl/simple_pages/templates/components.html
> +{% block title %}Components – CourtListener.com{% endblock %}
Nit:

```suggestion
{% block title %}Components Library – CourtListener.com{% endblock %}
```

2024-12-14 23:07 UTC, mlissner commented on cl/simple_pages/templates/components.html
> +    <h1 class="">Components</h1>
```suggestion
    <h1 class="">Components Library</h1>
```

2024-12-14 23:07 UTC, mlissner commented on cl/simple_pages/templates/components.html
Let's add a paragraph to this page explaining what it's for and why it exists.

2024-12-14 23:09 UTC, mlissner commented
I'm setting this for Eduardo's next sprint, but Ashkon, if you can address my suggestions before then, that'd be great.

2025-01-15 03:13 UTC, ERosendo commented on cl/settings/django.py
> +    "theme",
> In Big Cases, we put this in the web app, but even that feels off. Maybe it belongs in the cl.assets directory?

I attempted to configure the assets directory as the target for Tailwind's asset generation, but encountered the following error: `cl.assets is not in INSTALLED_APPS`. This suggests that the directory specified for the Tailwind command must be registered within the `INSTALLED_APPS` setting.

To resolve this, we can either leverage an existing module such as `simple_pages` or explicitly include the dotted path to the asset folder in the `INSTALLED_APPS` list.

2025-01-15 03:17 UTC, ERosendo commented on cl/assets/templates/base.html
> +  <link href="{% static "css/app.css" %}" rel="stylesheet">
> Honestly not sure what the preload vs. regular do

According to the documentation, the {% tailwind_css %} tag generates a stylesheet link for the app that has all the tailwind assets. This is the only step required to include Tailwind CSS on a page. The preload tag generates a preload directive for the stylesheet, which improves loading performance in production.

2025-01-15 18:16 UTC, mlissner commented on cl/settings/django.py
> +    "theme",
No harm in adding it to INSTALLED_APPS, right?

2025-01-22 20:02 UTC, closed without merging